const user = require('./user.js');
const comorbidity = require('./comorbidity.js');
const symptom = require('./symptom.js');
const medicalCompliance = require('./medical-compliance.js');
const country = require('./country.js');
const county = require('./county.js');
const subcounty = require('./subcounty.js');
const medicationAllergy = require('./medication-allergy.js');
const patient = require('./patient.js');
const patientMedicalAllergy = require('./patient-medical-allergy.js');
const patientComorbidity = require('./patient-comorbidity.js');
const riskFactor = require('./risk-factor.js');
const patientRiskFactor = require('./patient-risk-factor.js');
const glucoseLog = require('./glucose-log.js');
const bpLog = require('./bplog.js');
const patientMedicationCompliance = require('./patient-medication-compliance.js');
const patientSymptom = require('./patient-symptom.js');
const organization = require('./organization.js');
const facilityType = require('./facility-type.js');
const facility = require('./facility.js');
const patientTransfer = require('./patient-transfer.js');
const patientTransferHistory = require('./patient-transfer-history.js');
const patientTransferUpdate = require('./patient-transfer-update.js');
const bpLogUpdate = require('./bplog-update.js');
const redRiskNotification = require('./red-risk-notification.js');
const bpLogDetail = require('./bplog-detail.js');
const labTest = require('./lab-test.js');
const patientLabTest = require('./patient-lab-test');
const htnPlan = require('./htn-plan.js');
const htnPlanHistory = require('./htn-plan-history.js');
const htnPlanUpdate = require('./htnplan-update.js');
const patientMedicalReview = require('./patient-medical-review.js');
const clinicalReviewNote = require('./clinical-review-note.js');
const nutritionCounseling = require('./nutrition-counseling.js');
const physicalExamination = require('./physical-examination.js');
const complication = require('./complication.js');
const healthcareUtilization = require('./healthcare-utilization.js');
const patientMedicalReviewUpdate = require('./patient-medical-review-update.js');
const trainingMaterial = require('./training-material.js');
const network = require('./network.js');
const facilityNetwork = require('./facility-network.js');
const networkUpdate = require('./network-update.js');
const dosageFrequency = require('./dosage-frequency.js');
const dosageUnit = require('./dosage-unit.js');
const bpcheckFrequency = require('./bpcheck-frequency.js');
const hba1cCheckFrequency = require('./hba1c-check-frequency.js');
const frequency = require('./frequency.js');
const deviceDetails = require('./device-details.js');
const patientReviewLog = require('./patient-review-log.js');
const screeningLog = require('./screening-log.js');
const brand = require('./migrate-brand.js');
const classification = require('./migrate-classification.js');
const classificationbrand = require('./migrate-classificationbrand.js');
const countryclassification = require('./migrate-country-classification.js');
const dosageform = require('./migrate-dosageform.js');
const medication = require('./migrate-medication.js');
const medicationcountrydetail = require('./migrate-medication-country-detail.js');
const prescription = require('./migrate-prescription.js');
const fillprescription = require('./migrate-fillprescription.js');
const fillprescriptionhistory = require('./migrate-fill-prescription-history.js');
const prescriptionhistory = require('./migrate-prescription-history.js');
const updateprescription = require('./update-prescriptions.js');
const updatefillprescription = require('./update-fillprescription.js');
const patientUpdate = require('./patient-update.js');
const version = require('./version.js');
const role = require('./role.js');
const rolePermission = require('./role-permission.js');
// const cloneRoles = require('./clone-roles.js');
const cloneForms = require('./clone-forms.js');
const userUpdate = require('./user-update.js');
const cloneTriggers = require('./clone-triggers');
const facilityUpdate = require('./facility-update.js');
const medicalReviewFrequency = require('./medical-review-frequency.js');

async function test() {
  try {
    await user();
    await comorbidity();
    await symptom();
    await medicalCompliance();
    await country();
    await county();
    await subcounty();
    await medicationAllergy();
    await organization();
    await facilityType();
    await facility();
    await patient();
    await patientMedicalAllergy();
    await patientComorbidity();
    await riskFactor();
    await patientRiskFactor();
    await glucoseLog();
    await bpLog();
    await patientMedicationCompliance();
    await patientSymptom();
    await patientTransfer();
    await patientTransferHistory();
    await patientTransferUpdate();
    await bpLogUpdate();
    await redRiskNotification();
    await bpLogDetail();
    await labTest();
    await patientLabTest();
    await htnPlan();
    await htnPlanHistory();
    await htnPlanUpdate();
    await patientMedicalReview();
    await clinicalReviewNote();
    await nutritionCounseling();
    await physicalExamination();
    await complication();
    await healthcareUtilization();
    await patientMedicalReviewUpdate();
    await trainingMaterial();
    await network();
    await facilityNetwork();
    await networkUpdate();
    await dosageFrequency();
    await dosageUnit();
    await bpcheckFrequency();
    await hba1cCheckFrequency();
    await frequency();
    await deviceDetails();
    await patientReviewLog();
    await screeningLog();
    await brand();
    await classification();
    await classificationbrand();
    await countryclassification();
    await dosageform();
    await medication();
    await medicationcountrydetail();
    await prescription();
    await fillprescription();
    await fillprescriptionhistory();
    await prescriptionhistory();
    await updateprescription();
    await updatefillprescription();
    await patientUpdate();
    await version();
    await role();
    await rolePermission();
    // await cloneRoles();
    await cloneForms();
    await userUpdate();
    await cloneTriggers();
    await facilityUpdate();
    await medicalReviewFrequency();
    process.exit();
  } catch (error) {
    console.log('error--------', error)
  }
}


module.exports = test();